services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - mongodb/.env.mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/data:/data/db
    
    # for development
    ports:
      - "27017:27017"

  bot:
    build: ./bot
    restart: always
    volumes:
      - ./config-docker.yaml:/bot/config.yaml

      # For development
      - ./bot/:/bot/

    depends_on:
      - mongo