services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example